//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IurAir.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IurAir.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ident;iso_country;iata_code
        ///NTGA;PF;AAA
        ///YARY;AU;AAB
        ///HEAR;EG;AAC
        ///AAD;SO;AAD
        ///DABB;DZ;AAE
        ///KAAF;US;AAF
        ///SSYA;BR;AAG
        ///EDKA;DE;AAH
        ///SWRA;BR;AAI
        ///SR-AAJ;SR;AAJ
        ///NGUK;KI;AAK
        ///EKYT;DK;AAL
        ///FAMD;ZA;AAM
        ///OMAL;AE;AAN
        ///SVAN;VE;AAO
        ///URKA;RU;AAQ
        ///EKAH;DK;AAR
        ///ID-AAS;ID;AAS
        ///CN-0113;CN;AAT
        ///NSAU;WS;AAU
        ///RPMA;PH;AAV
        ///SBAX;BR;AAX
        ///OYGD;YE;AAY
        ///MGQZ;GT;AAZ
        ///UNAA;RU;ABA
        ///DNAS;NG;ABB
        ///LEAB;ES;ABC
        ///OIAA;IR;ABD
        ///KABE;US;ABE
        ///NGAB;KI;ABF
        ///YABI;AU;ABG
        ///YAPH;AU;ABH
        ///KABI;US;ABI
        ///DIAP;CI;ABJ
        ///HAKD;ET;ABK
        ///PAFM;US;ABL
        ///YBAM;AU;A [stringa troncata]&quot;;.
        /// </summary>
        internal static string Airports {
            get {
                return ResourceManager.GetString("Airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        /// </summary>
        internal static System.Drawing.Icon plane {
            get {
                object obj = ResourceManager.GetObject("plane", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AIRLINE_NAME;IATA_DESIGNATOR;DIGIT_CODE
        ///ABX Air;GB;832
        ///Aegean Airlines;A3;390
        ///Aer Lingus;EI;53
        ///Aero Republica;P5;845
        ///Aeroflot;SU;555
        ///Aerolineas Argentinas;AR;44
        ///Aeromar;VW;942
        ///Aeromexico;AM;139
        ///Africa World Airlines;AW;394
        ///Afrijet;J7;277
        ///Air Algérie;AH;124
        ///Air Arabia;G9;514
        ///Air Astana;KC;465
        ///Air Austral;UU;760
        ///Air Baltic;BT;657
        ///Air Botswana;BP;636
        ///Air Burkina;2J;226
        ///Air Cairo;SM;381
        ///Air Caledonie;TY;190
        ///Air Canada;AC;14
        ///Air Caraibes;TX;427
        ///Air Changan;9H;856
        ///Air China;CA;999
        ///Air Cors [stringa troncata]&quot;;.
        /// </summary>
        internal static string Vettori {
            get {
                return ResourceManager.GetString("Vettori", resourceCulture);
            }
        }
    }
}
